add caching

diff --git a/.github/workflows/integration-m3o.yml b/.github/workflows/integration-m3o.yml
--- a/.github/workflows/integration-m3o.yml
+++ b/.github/workflows/integration-m3o.yml
@@ -21,19 +21,42 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Enable caching
-      uses: actions/cache@v2
+      # We would use the official actions/cache@v2, but it doesn't save the cache if the build fails
+      # caches are scoped to a branch but will also check the default branch upon cache miss
+      uses: pat-s/always-upload-cache@v2.0.0 
       with:
         path: ~/go/pkg/mod
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-go-
+
     - name: Install micro
       run: |
-        go install
+        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build # this is used by the Docker image
+        go install # this is used by the tests themselves
 
-    - name: Build container
+    # This sets up a local docker registry to cache 
+    # Based on https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei
+    - name: Setup docker caching
+      id: cache-docker
+      # We would use the official actions/cache@v2, but it doesn't save the cache if the build fails
+      # caches are scoped to a branch but will also check the default branch upon cache miss
+      uses: pat-s/always-upload-cache@v2.0.0
+      with:
+        path: /tmp/docker-registry
+        key: docker-registry-${{ hashFiles('test/Dockerfile', 'micro') }}
+    - name: Setup docker registry
       run: |
-        bash scripts/test-docker.sh
+        docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2 && npx wait-on tcp:5000
+        docker pull localhost:5000/micro || true
+    - name: Build docker image
+      run: |
+        docker build -f test/Dockerfile . -t micro --cache-from=localhost:5000/micro
+    - name: Tag and push docker
+      run: |
+        docker tag micro localhost:5000/micro && docker push localhost:5000/micro || true
+      if: steps.cache-docker.outputs.cache-hit != 'true'
+
 
     - name: Test micro server
       working-directory: ./test
